title: Produit
nav:
    - index.md
    - Mini-KVM:
        - minikvm/index.md
        - minikvm/whats-in-the-box.md
        - minikvm/features.md
        - ../app/basic.md
        - minikvm/how-to-connect.md
        - Comment ça marche: /faq/usbkvm/kvm-over-usb/
        - Avis & Presse: minikvm/reviews.md
        - minikvm/specifications.md
        - minikvm/usb-switch.md
        - minikvm/extension-pins.md
        - FAQ & Dépannage: /faq/minikvm/op-minikvm/
        - Pourquoi Openterface: /faq/usbkvm/openterface/
    - Accessoires:
        - accessories/index.md
        - Câble VGA vers HDMI 1m: accessories/vga-to-hdmi-cable.md
        - Câble Type-C vers C Nylon 1.5m: accessories/nylong-c-to-c-150.md
        - Câble Type-C vers C Orange 1.5m: accessories/type-c-to-c-cable-with-adapter.md
        - Câble Type-C vers A Noir 30cm: accessories/black-c-to-a-30.md
        - Câble HDMI 30cm: accessories/hdmi-male-to-male-cable.md
        - Sac à Outils: accessories/openterface-toolkit-bag.md