authors:
  TechxArtisan:
    name: TechxArtisan Studio
    description: Un studio créatif et une communauté de passionnés de technologie.
    avatar: /images/txa-avatar.jpg

  Openterface:
    name: Openterface 
    description: Salut !
    avatar: /images/op-avatar.jpg