authors:
  TechxArtisan:
    name: TechxArtisan
    description: Un studio créatif et une communauté d'enthousiastes de la technologie.
    avatar: /images/txa-avatar.jpg

  Openterface:
    name: Openterface
    description: Bonjour à tous !
    avatar: /images/op-avatar.jpg

  CNXSOFT:
    name: JEAN-LUC AUFRANC CNXSOFT
    description: Jean-Luc a commencé CNX Software en 2010 comme une activité à temps partiel, avant de quitter son emploi de responsable de l'ingénierie logicielle et de commencer à écrire des nouvelles et des critiques quotidiennes à plein temps plus tard en 2011.